### PR TITLE
Typo: "asynchornous"

### PR DESCRIPTION
**Pull request by tommythorn**
Spotted a typo

### CODE REVIEW

**Comment by brabect1** [comment]
Hi Tommy,
Thanks for corrections. Let me know, please, once you are through so that I will merge this PR.
Kind regards!

**Comment by tommythorn** [comment]
Indeed a have a few more to follow, maybe later today.

**Comment by tommythorn** [comment]
I actually didn't realize all my incremental updates ended up here.  Sorry about that.  I have fixed some more and squashed it all into a single commit.  Hope it's useful.

Thanks for your tutorial.  Very helpful, thought I'm still learning.

I wonder if I might ask you about timing analysis?  Until recently I never needed more than the simple setup checks for synchronous logic, but now I'm implementing asynchronous logic, in particular bundled-data with delay matching, and I'm trying to understand how to coax STA (OpenSTA in particular) into helping me find (and check) the delays I need to add to the control path.

I taped out https://github.com/tommythorn/tt08-maxbw, with hopefully absurdly large delays, as I hadn't figured this out in time, but I hope to do better for the next one.

PS: My C elements aren't latches in the above, but it would be easy enough fix if that would help.

**Comment by brabect1** [comment]
In my opinion, STA would not work well for asynchronous logic. You could potentially use it as a tool to get insight into delays of some paths but it would be manual process and quite often, I would expect, you wouldn't be getting exactly what you want. I would draw similarity with analog design that relies on "right by design" rather than "right by methodology" used in synchronous, digital design.

**Review by brabect1 — APPROVED** [review]

**Comment by tommythorn** [comment]
Thanks for your comments.  Unfortunately STA is the only available option for static timing and I will have to make it work.  There is no “correct by construction” possible for bundled data.

**Pull request merged**
